import { SITE_URL } from "../seo";
import { ORG_ID } from "../structured-data";
import publicSignatories from "./signatories.public.generated.json";

/**
 * The publicly-named accountable signatories, projected from the compliance signatory registry
 * (docs/legal/signatories.json → generated by scripts/generate-signatories-public.mjs, drift-gated
 * in CI). Kept in its own module — NOT in the sitewide structured-data.ts, which ships on every page
 * via the root-layout JsonLd — so this /about-only data lands only in the About route chunk.
 */
export const PUBLIC_SIGNATORIES = publicSignatories.signatories;

/**
 * schema.org `Person` nodes for the publicly-named accountable signatories. Each Person is linked to
 * the operating Organization by the shared `@id` (declared once in structured-data.ts's siteGraph)
 * via `worksFor`, and to their verified external identities (GitHub, LinkedIn) via `sameAs`. Emitted
 * on the About page. Factual and neutral by construction — name, role and public profile links only.
 */
export function signatoryPersonGraph() {
  return {
    "@context": "https://schema.org",
    "@graph": PUBLIC_SIGNATORIES.map((s) => ({
      "@type": "Person",
      "@id": `${SITE_URL}/about#${s.id}`,
      name: s.legalName,
      jobTitle: s.jobTitle,
      worksFor: { "@type": "Organization", "@id": ORG_ID, name: s.org },
      sameAs: s.sameAs,
    })),
  };
}
