/**
 * The comparison card's wording, apart from its paragraphs that carry emphasis or links, which are
 * components of their own (`Card*.svelte`): each piece with its values named, `{n}` for one (filled
 * with `$lib/template`). The card page fills them, and the build renders each once, its values
 * marked, into `states/card.html` for the iOS app to draw the same words from (ADR 0019 D4b).
 */
export const CARD_COPY = {
  loading: "Preparing your comparison…",
  archivedLinkKicker: "A link from the old how2vote.com.au",
  archivedLinkTitle: "This card can't be opened any more",
  archivedLinkOld:
    "This link points to a How2Vote card made on our old site. Cards made there were stored on that site's server, which has since been retired — so the card behind this link can't be retrieved.",
  archivedLinkNow:
    "Today, How2Vote works differently: your answers travel in the link itself, nothing is stored on a server, and a shared comparison keeps working — even offline.",
  archivedLinkAction: "Make a new card",
  errorTitle: "That link didn't work",
  errorNote: "We couldn't read the comparison from this link. You can build your own.",
  errorAction: "Start",
  unavailableTitle: "Temporarily unavailable",
  unavailableNote:
    "This comparison is temporarily unavailable while it is under review. This is a precaution — the material has been withdrawn until a check is complete. Please try again later.",
  unavailableAction: "Back to home",
  home: "How2Vote home",
  compareStage: "Your comparison",
  buildStage: "Your voting plan",
  demonstrationStage: "Historical demonstration plan",
  parliament: "The current Parliament",
  metaArchivedLink: "A card from the old How2Vote",
  metaParliament: "The current Parliament — How2Vote comparison",
  metaElectorate: "{electorate} — How2Vote {year} comparison",
  parliamentPanel: "Party voting-record alignment",
  parliamentPanelNote: "Current Parliament · House and Senate combined",
  parliamentCaption: "Party voting-record alignment (current Parliament)",
  house: "House of Representatives",
  houseCompare: "Green ballot paper · your local member",
  houseBuild: "Green ballot paper · number every box",
  houseCaption: "Party voting-record alignment (House parties)",
  senate: "Senate",
  senatePaper: "White ballot paper · {state}",
  senateCaption: "Party voting-record alignment (Senate groups)",
  shared:
    "This is a shared comparison. To build your own voting plan, make your own comparison first.",
  build: "Build my voting plan",
  buildDemonstration: "Build a demonstration plan",
  plansClosed:
    "Building a printable voting plan is not available right now. It becomes available once this election's official candidate list and ballot order are confirmed and verified and the printable-plan feature is switched on.",
  share: "Share this comparison",
  copied: "Link copied ✓",
  shareWarning: "Before you share",
  shareWarningTitle: "This link can't be recalled",
  copyLink: "Copy link",
  cancel: "Cancel",
  save: "Save on this device",
  savedOn: "Saved on this device ✓",
  whyShow: "Why do these parties align with my answers?",
  whyHide: "Hide the evidence",
  noPartyVotes: "no recorded party votes",
  partyScore: "{score}% party alignment",
  record: "record",
  recordLabel: "See the parliamentary voting record for “{question}” on They Vote For You",
  changeAnswers: "Change my answers",
  makeOwn: "Make my own comparison",
  houseComplete: "All {total} boxes numbered. Check them against your ballot paper.",
  houseProgress: "{ranked} of {total} numbered — number every box for a formal House vote.",
  senateMethod: "Senate voting method",
  above: "Above the line",
  below: "Below the line",
  senateOneMethod:
    "Choose one method only — if you number above the line, leave the boxes below it blank.",
  group: "Group {group}",
  column: "Column {group}",
  columnOne: "Column {group} · {n} candidate",
  columnMany: "Column {group} · {n} candidates",
  aboveProgress: "{ranked} numbered — number at least 6 boxes above the line.",
  belowProgress: "{ranked} numbered — number at least 12 boxes below the line.",
  territoryProgress: "{ranked} numbered.",
  print: "Print my voting plan",
  printDemonstration: "Print this demonstration",
  backToCompare: "Back to the comparison",
  preferenceFor: "Preference number for {name}",
  higher: "Give {name} a higher preference",
  lower: "Give {name} a lower preference",
  independent: "Independent",
} as const;
