import { readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { GLOSSARY } from "./content/glossary";

/**
 * Source-level invariants for the app's three link conventions. All three fail the same silent way
 * — the link keeps working, so nothing breaks; it just stops doing the thing it was changed to do —
 * which is exactly the class of regression a behavioural test does not catch.
 *
 *   1. A link that opens a new tab says so. The cue has to be generated by ExternalLink rather
 *      than hand-written per anchor, or the next anchor added is unannounced again.
 *   2. A glossary deep link resolves. /glossary#division is not validated by anything — the anchor
 *      just silently lands at the top of the page if the id is renamed.
 *   3. The documents the dialog can raise are the documents that exist at those paths.
 */

const SRC = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const rel = (path: string): string => path.slice(SRC.length + 1);

function sourceFiles(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) return sourceFiles(path);
    return /\.(svelte|ts)$/.test(entry) && !entry.endsWith(".test.ts") ? [path] : [];
  });
}

const files = sourceFiles(SRC).map((path) => ({ path, source: readFileSync(path, "utf8") }));

describe("new-tab links are announced", () => {
  it("finds the app source", () => {
    // Guards the guard: an empty or tiny file list would make every assertion below vacuous.
    expect(files.length).toBeGreaterThan(100);
    expect(files.map((f) => rel(f.path))).toContain("lib/components/ExternalLink.svelte");
  });

  it("only ExternalLink opens a new tab", () => {
    const offenders = files
      .filter(({ path }) => rel(path) !== "lib/components/ExternalLink.svelte")
      .filter(({ source }) => source.includes('target="_blank"'))
      .map(({ path }) => rel(path));
    expect(
      offenders,
      'use <ExternalLink> — a raw target="_blank" gives the reader no warning that the link ' +
        "leaves the page (and, in the native shells, the app). If a comment needs the literal " +
        "string, reword it.",
    ).toEqual([]);
  });

  it("ExternalLink puts the cue in the accessible name", () => {
    const source = readFileSync(join(SRC, "lib/components/ExternalLink.svelte"), "utf8");
    // Both branches matter and neither is reachable from the other: an aria-label REPLACES the
    // element's contents for assistive tech, so a hidden span inside it is never announced.
    expect(source).toMatch(/class="visually-hidden"/);
    expect(source).toMatch(/ariaLabel \? `\$\{ariaLabel\} \(\$\{cue\}\)`/);
    expect(source).toMatch(/rel=\{relValue\}/);
    expect(source).toMatch(/"noopener", "noreferrer"/);
  });
});

describe("glossary references resolve", () => {
  const ids = new Set(GLOSSARY.map((entry) => entry.id));

  it("has a term list to check against", () => {
    expect(ids.size).toBeGreaterThan(5);
  });

  it("every id is unique and anchor-safe", () => {
    expect(ids.size).toBe(GLOSSARY.length);
    for (const { id } of GLOSSARY)
      expect(id, `${id} is not a kebab-case anchor`).toMatch(/^[a-z0-9-]+$/);
  });

  it("every <GlossaryTerm> and /glossary# reference names a defined term", () => {
    const missing: string[] = [];
    for (const { path, source } of files) {
      if (rel(path) === "lib/content/glossary.ts") continue;
      for (const [, id] of source.matchAll(/<GlossaryTerm\s+id="([^"]+)"/g)) {
        if (!ids.has(id)) missing.push(`${rel(path)}: <GlossaryTerm id="${id}">`);
      }
      for (const [, id] of source.matchAll(/["'`]\/glossary#([a-z0-9-]+)/g)) {
        if (!ids.has(id)) missing.push(`${rel(path)}: /glossary#${id}`);
      }
    }
    expect(missing, "these point at a glossary term that no longer exists").toEqual([]);
  });
});

describe("the document dialog's registry", () => {
  const source = readFileSync(join(SRC, "lib/components/DocLink.svelte"), "utf8");
  const entries = [
    ...source.matchAll(/"(\/[a-z-]+)":\s*\{[^}]*?import\("\$lib\/(content\/[\w.]+)"\)/gs),
  ];

  it("registers every document against a real content component and a real route", () => {
    expect(entries.length).toBeGreaterThan(2);
    for (const [, href, module] of entries) {
      // The content component the dialog renders must exist …
      expect(
        files.map((f) => rel(f.path)),
        `${href} → ${module}`,
      ).toContain(`lib/${module}`);
      // … and so must the page it links out to, because the dialog offers "Open the full page" and
      // the anchor is a real href that must not 404.
      expect(
        files.map((f) => rel(f.path)),
        `${href} has no route — the dialog's fallback link would 404`,
      ).toContain(`routes${href}/+page.svelte`);
    }
  });

  it("each route renders the same component the dialog does", () => {
    for (const [, href, module] of entries) {
      const route = files.find((f) => rel(f.path) === `routes${href}/+page.svelte`);
      const name = module.replace(/^content\//, "").replace(/\.svelte$/, "");
      // If the page stopped rendering the shared body, the dialog and the page would be two copies
      // of the same document, free to drift — which for /privacy and /terms is a compliance problem,
      // not just an inconsistency.
      expect(route?.source, `${href} must render <${name}>`).toContain(`<${name} />`);
    }
  });
});
