/**
 * Pre-projected electorate boundary maps for the ballot confirmation screen. Generated by
 * `pnpm data:maps` (packages/data-pipeline/src/bin/build-maps.ts) from AEC boundary data and
 * committed under static/maps/, so they ride the service-worker precache and render offline.
 */

export type CityMarker = { name: string; x: number; y: number };
export type DivisionShape = {
  name: string;
  path: string;
  /** [x, y, width, height] in viewBox units. */
  bbox: [number, number, number, number];
};
export type StateMap = {
  state: string;
  attribution: string;
  /** [width, height]; origin is 0 0. */
  viewBox: [number, number];
  divisions: DivisionShape[];
  cities: CityMarker[];
};

const cache = new Map<string, Promise<StateMap>>();

/**
 * Boundary sets are per election vintage (divisions and their shapes differ between elections);
 * only vintages with a directory under static/maps/ have maps — for the others the fetch 404s
 * and the confirmation screen simply renders without a map, which is more honest than showing
 * another election's boundaries.
 */
export function loadStateMap(electionId: string, stateCode: string): Promise<StateMap> {
  const key = `${electionId}/${stateCode.toUpperCase()}`;
  let promise = cache.get(key);
  if (!promise) {
    promise = fetch(`/maps/${key}.json`).then((r) => {
      if (!r.ok) throw new Error(`map ${key}: HTTP ${r.status}`);
      return r.json() as Promise<StateMap>;
    });
    // A failed fetch shouldn't poison the cache — retry next time the screen mounts.
    promise.catch(() => cache.delete(key));
    cache.set(key, promise);
  }
  return promise;
}
